#!/usr/bin/env python3
"""Merge all agent outputs into a single query_plans.py file."""

import json
import glob
import os

def main():
    agents_dir = '/Users/josh/Desktop/econstats/agents'
    output_file = '/Users/josh/Desktop/econstats/query_plans.py'

    # Find all plan JSON files
    plan_files = glob.glob(os.path.join(agents_dir, 'plans_*.json'))

    print(f"Found {len(plan_files)} plan files to merge:")
    for f in plan_files:
        print(f"  - {os.path.basename(f)}")

    # Merge all plans
    all_plans = {}
    for plan_file in plan_files:
        try:
            with open(plan_file, 'r') as f:
                plans = json.load(f)
                all_plans.update(plans)
                print(f"  Loaded {len(plans)} plans from {os.path.basename(plan_file)}")
        except Exception as e:
            print(f"  ERROR loading {plan_file}: {e}")

    # Write merged output
    with open(output_file, 'w') as f:
        f.write('"""')
        f.write('\nAuto-generated query plans for common economic prompts.')
        f.write('\nGenerated by specialized AI economist agents.')
        f.write(f'\nTotal plans: {len(all_plans)}')
        f.write('\n"""\n\n')
        f.write('QUERY_PLANS = ')
        f.write(json.dumps(all_plans, indent=2))
        f.write('\n')

    print(f"\n{'='*60}")
    print(f"MERGE COMPLETE!")
    print(f"{'='*60}")
    print(f"Total plans merged: {len(all_plans)}")
    print(f"Output written to: {output_file}")


if __name__ == "__main__":
    main()
